-- TS-M1-A2 — M1 schema subset (PostgreSQL dialect).
--
-- @implements BS-091: PostgreSQL migrations for the M1 schema subset.
-- @implements FS-091.1: Logical data model (M1 subset only).
-- @implements FS-091.2: Dual ticket identifiers (internal ticket_id + external ticketID).
-- @implements BS-091.1: Composite UNIQUE (ticketID, email).
-- @implements FS-091.3: Ticket open/closed status (text + CHECK).
-- @implements FS-091.4: Thread entry type M/R/N (text + CHECK).
--
-- Modernisation note (ROADMAP Decisions): this replaces the legacy MySQL install
-- stream (supersedes FS-060/FS-061). Only the tables the M1 slice touches are
-- created; later milestones extend the 34-table model incrementally.
--
-- Conventions:
--   * legacy MySQL types are mapped to Postgres: tinyint(1)->boolean,
--     int unsigned->integer/bigint, datetime->timestamptz.
--   * enums are modelled as text + a CHECK constraint (NOT native PG enum types)
--     so later milestones extend the value set without ALTER TYPE churn.
--   * every object uses IF NOT EXISTS so a second `sqlx migrate run` is a safe
--     no-op even outside the migrator's own tracking table (AC-2 idempotency).
--   * column/enum literals match FS-091 names so later milestones extend cleanly.

-- ---------------------------------------------------------------------------
-- department — routing unit (FS-091, entity 8).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS department (
    dept_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name          text        NOT NULL,
    dept_signature     text        NOT NULL DEFAULT '',
    ispublic           boolean     NOT NULL DEFAULT true,
    ticket_auto_response boolean   NOT NULL DEFAULT true,
    message_auto_response boolean  NOT NULL DEFAULT true,
    created            timestamptz NOT NULL DEFAULT now(),
    updated            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT department_dept_name_key UNIQUE (dept_name)
);

-- ---------------------------------------------------------------------------
-- sla — service-level plan (FS-091.6, entity 12). Minimal + nullable for M1.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sla (
    id                          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        text        NOT NULL,
    grace_period                integer     NOT NULL DEFAULT 48,
    isactive                    boolean     NOT NULL DEFAULT true,
    enable_priority_escalation  boolean     NOT NULL DEFAULT true,
    disable_overdue_alerts      boolean     NOT NULL DEFAULT false,
    notes                       text        NULL,
    created                     timestamptz NOT NULL DEFAULT now(),
    updated                     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT sla_name_key UNIQUE (name)
);

-- ---------------------------------------------------------------------------
-- groups — staff permission role (FS-091, entity 16). Named `groups` because
-- `group` is a PostgreSQL reserved word. M1 carries the flags the slice needs;
-- the rest of the permission matrix is added when later milestones use it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS groups (
    group_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name          text        NOT NULL,
    group_enabled       boolean     NOT NULL DEFAULT true,
    can_create_tickets  boolean     NOT NULL DEFAULT false,
    can_post_reply      boolean     NOT NULL DEFAULT false,
    notes               text        NULL,
    created             timestamptz NOT NULL DEFAULT now(),
    updated             timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- group_dept_access — which departments a group may work (FS-091, entity 17).
-- Composite unique key (group_id, dept_id).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS group_dept_access (
    group_id integer NOT NULL REFERENCES groups (group_id) ON DELETE CASCADE,
    dept_id  integer NOT NULL REFERENCES department (dept_id) ON DELETE CASCADE,
    CONSTRAINT group_dept_access_pkey PRIMARY KEY (group_id, dept_id)
);

-- ---------------------------------------------------------------------------
-- staff — staff user account (FS-091, entity 15). `passwd` holds the argon2id
-- hash (TS-M1-A4a). unique `username`.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff (
    staff_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   integer     NOT NULL REFERENCES groups (group_id),
    dept_id    integer     NOT NULL REFERENCES department (dept_id),
    username   text        NOT NULL,
    firstname  text        NOT NULL DEFAULT '',
    lastname   text        NOT NULL DEFAULT '',
    passwd     text        NOT NULL,
    email      text        NOT NULL DEFAULT '',
    phone      text        NOT NULL DEFAULT '',
    phone_ext  text        NOT NULL DEFAULT '',
    signature  text        NOT NULL DEFAULT '',
    isactive   boolean     NOT NULL DEFAULT true,
    isadmin    boolean     NOT NULL DEFAULT false,
    isvisible  boolean     NOT NULL DEFAULT true,
    created    timestamptz NOT NULL DEFAULT now(),
    lastlogin  timestamptz NULL,
    updated    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT staff_username_key UNIQUE (username)
);

-- ---------------------------------------------------------------------------
-- ticket — the central work item (FS-091.2, entity 1).
-- Dual identifiers: surrogate ticket_id PK + external 6-digit ticketID.
-- Enum-valued columns (status, source) are text + CHECK.
-- Composite UNIQUE (ticketID, email) per BS-091.1.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ticket (
    ticket_id   bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ticketID"  bigint      NOT NULL,
    dept_id     integer     NOT NULL REFERENCES department (dept_id),
    sla_id      integer     NULL REFERENCES sla (id),
    staff_id    integer     NULL REFERENCES staff (staff_id),
    priority_id integer     NOT NULL DEFAULT 2,
    topic_id    integer     NOT NULL DEFAULT 0,
    team_id     integer     NOT NULL DEFAULT 0,
    email       text        NOT NULL,
    name        text        NOT NULL DEFAULT '',
    phone       text        NOT NULL DEFAULT '',
    phone_ext   text        NOT NULL DEFAULT '',
    subject     text        NOT NULL DEFAULT '[no subject]',
    ip_address  text        NOT NULL DEFAULT '',
    status      text        NOT NULL DEFAULT 'open',
    source      text        NOT NULL DEFAULT 'Web',
    isoverdue   boolean     NOT NULL DEFAULT false,
    isanswered  boolean     NOT NULL DEFAULT false,
    duedate     timestamptz NULL,
    reopened    timestamptz NULL,
    closed      timestamptz NULL,
    lastmessage timestamptz NULL,
    lastresponse timestamptz NULL,
    created     timestamptz NOT NULL DEFAULT now(),
    updated     timestamptz NOT NULL DEFAULT now(),
    -- FS-091.3: status is exactly one of open|closed (text + CHECK).
    CONSTRAINT ticket_status_check CHECK (status IN ('open', 'closed')),
    -- FS-091.9: ticket source set.
    CONSTRAINT ticket_source_check CHECK (source IN ('Web', 'Email', 'Phone', 'API', 'Other')),
    -- BS-091.1: the DB enforces uniqueness on the composite (ticketID, email).
    CONSTRAINT ticket_ticketid_email_key UNIQUE ("ticketID", email)
);

-- ---------------------------------------------------------------------------
-- ticket_thread — one conversation entry (FS-091.4, entity 2).
-- thread_type is exactly one of M (Message) | R (Response) | N (Note).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ticket_thread (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   bigint      NOT NULL REFERENCES ticket (ticket_id) ON DELETE CASCADE,
    pid         bigint      NOT NULL DEFAULT 0,
    staff_id    integer     NULL REFERENCES staff (staff_id),
    thread_type text        NOT NULL,
    poster      text        NOT NULL DEFAULT '',
    source      text        NOT NULL DEFAULT '',
    title       text        NULL,
    body        text        NOT NULL DEFAULT '',
    ip_address  text        NOT NULL DEFAULT '',
    created     timestamptz NOT NULL DEFAULT now(),
    updated     timestamptz NOT NULL DEFAULT now(),
    -- FS-091.4: thread_type is exactly M|R|N (text + CHECK, no native enum).
    CONSTRAINT ticket_thread_type_check CHECK (thread_type IN ('M', 'R', 'N'))
);

CREATE INDEX IF NOT EXISTS ticket_thread_ticket_id_idx ON ticket_thread (ticket_id);

-- ---------------------------------------------------------------------------
-- session — persisted login session (FS-091, entity 18). DB-backed sessions
-- (ROADMAP Decision 1). `session_id` is the natural primary key.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS session (
    session_id      text        PRIMARY KEY,
    session_data    text        NOT NULL DEFAULT '',
    session_expire  timestamptz NULL,
    session_updated timestamptz NOT NULL DEFAULT now(),
    user_id         integer     NOT NULL DEFAULT 0,
    user_ip         text        NOT NULL DEFAULT '',
    user_agent      text        NOT NULL DEFAULT ''
);

-- ---------------------------------------------------------------------------
-- config — key/value system configuration (FS-091, entity). `updated`
-- auto-bumps in the application layer (BS-091.11).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS config (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key     text        NOT NULL,
    value   text        NOT NULL DEFAULT '',
    updated timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT config_key_key UNIQUE (key)
);
