-- TS-M2-A1 — M2 attachment storage schema (PostgreSQL dialect).
--
-- @implements FS-022.12: Content-addressed file storage (modernised — DEVIATION
--   D1: a filesystem blob store keyed by content SHA-256, NOT the legacy chunked
--   DB table). `attachment_file` is the metadata row; the bytes live on disk at
--   `<BLOB_ROOT>/aa/bb/<sha256>` (the BlobStore in ost_core). Real byte-level
--   dedup: identical content → one blob → one `attachment_file` row (its `hash`
--   is UNIQUE). This obsoletes the legacy time-salted KL-022.4 quirk.
-- @implements FS-022 data requirements: a stored file carries mime, byte size,
--   original name, a content hash, and a creation timestamp.
-- @implements FS-091.4 (ref): ticket_attachment.ref_type reuses the thread entry
--   type domain M (Message) / R (Response) / N (Note).
--
-- Conventions (carried from 0001): IF NOT EXISTS for idempotency; enum-valued
-- columns are text + CHECK (no native PG enum); timestamptz for timestamps.

-- ---------------------------------------------------------------------------
-- attachment_file — file metadata, one row per distinct content hash.
-- The `hash` is the lowercase hex SHA-256 of the file bytes and is UNIQUE, so a
-- second upload of identical bytes upserts onto the same row (real dedup, D1).
-- `storage_key` is the on-disk relative key `aa/bb/<sha256>` under BLOB_ROOT.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attachment_file (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mime        text        NOT NULL DEFAULT 'application/octet-stream',
    size        bigint      NOT NULL DEFAULT 0,
    hash        text        NOT NULL,
    name        text        NOT NULL DEFAULT '',
    storage_key text        NOT NULL DEFAULT '',
    created     timestamptz NOT NULL DEFAULT now(),
    -- D1: identical content shares one row (the content SHA-256 is the dedup key).
    CONSTRAINT attachment_file_hash_key UNIQUE (hash)
);

-- ---------------------------------------------------------------------------
-- ticket_attachment — binds a stored file to a ticket and a specific thread
-- entry. `ref_type` mirrors the thread entry type (M/R/N) the file is attached
-- to. `file_id` → attachment_file; `ref_id` → ticket_thread entry.
-- A binding is removed when its ticket (and thus its thread entries) is removed.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ticket_attachment (
    id        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint  NOT NULL REFERENCES ticket (ticket_id) ON DELETE CASCADE,
    file_id   bigint  NOT NULL REFERENCES attachment_file (id),
    ref_id    bigint  NOT NULL REFERENCES ticket_thread (id) ON DELETE CASCADE,
    ref_type  text    NOT NULL,
    created   timestamptz NOT NULL DEFAULT now(),
    -- ref_type is exactly M|R|N (text + CHECK, no native enum).
    CONSTRAINT ticket_attachment_ref_type_check CHECK (ref_type IN ('M', 'R', 'N'))
);

CREATE INDEX IF NOT EXISTS ticket_attachment_ticket_id_idx ON ticket_attachment (ticket_id);
CREATE INDEX IF NOT EXISTS ticket_attachment_file_id_idx ON ticket_attachment (file_id);
CREATE INDEX IF NOT EXISTS ticket_attachment_ref_id_idx ON ticket_attachment (ref_id);
