-- TS-M2-D1 — M2 canned-response schema (PostgreSQL dialect).
--
-- @implements FS-022.14: Canned (pre-written) responses — a reusable response
--   body, optionally scoped to a department and optionally carrying attachments,
--   offered in the staff reply composer. `canned_response` is the body row;
--   `canned_attachment` binds a stored file (D1 blob store) to a canned response.
-- @implements BS-022.1: a canned response is offerable when its `dept_id` is 0
--   (all departments) OR matches the ticket's department.
-- @implements BS-022.2: only ENABLED canned responses are offerable; a disabled
--   one is filtered out of the list and not fetchable (404).
--
-- Conventions (carried from 0001/0003): IF NOT EXISTS for idempotency;
-- enum/boolean-valued columns mapped to PG types; timestamptz for timestamps;
-- `dept_id = 0` is the legacy "all departments" sentinel (NOT an FK — 0 is not a
-- real department row), so `dept_id` is a plain integer, not a REFERENCES.

-- ---------------------------------------------------------------------------
-- canned_response — a reusable, pre-written response body (FS-022.14).
-- `title` is UNIQUE (the authoring + dropdown label key). `dept_id = 0` means
-- "all departments"; a non-zero value scopes the response to that department.
-- `isenabled` gates whether it is offered at all (BS-022.2).
-- `response` holds the body (legacy column name); `notes` is internal-only.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS canned_response (
    canned_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id   integer     NOT NULL DEFAULT 0,
    isenabled boolean     NOT NULL DEFAULT true,
    title     text        NOT NULL,
    response  text        NOT NULL DEFAULT '',
    notes     text        NULL,
    created   timestamptz NOT NULL DEFAULT now(),
    updated   timestamptz NOT NULL DEFAULT now(),
    -- BS-022.x: the title is the unique authoring/label key (a re-used title
    -- errors, so the seed + future CRUD never duplicates one).
    CONSTRAINT canned_response_title_key UNIQUE (title)
);

-- ---------------------------------------------------------------------------
-- canned_attachment — binds a stored file (attachment_file, D1) to a canned
-- response. A canned response may carry zero or more files; deleting the canned
-- response removes its bindings (but never the shared attachment_file blob,
-- which the reclamation half preserves while still referenced).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS canned_attachment (
    id        bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canned_id integer NOT NULL REFERENCES canned_response (canned_id) ON DELETE CASCADE,
    file_id   bigint  NOT NULL REFERENCES attachment_file (id),
    created   timestamptz NOT NULL DEFAULT now(),
    -- A file binds to a given canned response at most once.
    CONSTRAINT canned_attachment_canned_file_key UNIQUE (canned_id, file_id)
);

CREATE INDEX IF NOT EXISTS canned_attachment_canned_id_idx ON canned_attachment (canned_id);
CREATE INDEX IF NOT EXISTS canned_attachment_file_id_idx ON canned_attachment (file_id);
