-- TS-M3-schema — M3 schema expansion (PostgreSQL dialect).
--
-- @implements FS-091.9: Team entity (cross-department assignment group).
-- @implements FS-091.10: Team member junction table (staff-to-team membership).
-- @implements FS-091.11: Help topic entity (request category and routing defaults).
-- @implements FS-021.18: Ticket lock table for collaborative edit locking.
-- @implements BS-091.5: Team name unique constraint; help_topic (topic, topic_pid) unique.
--
-- Conventions (see 0001_m1_schema_subset.sql):
--   * every object uses IF NOT EXISTS so a second run is a safe no-op.
--   * column/enum literals match FS-091 names for consistency.

-- ---------------------------------------------------------------------------
-- team — cross-department assignment group (FS-091, entity 9).
-- Note: column is `isenabled` per FS-091 Entity #9, NOT `isactive`.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team (
    team_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text        NOT NULL,
    isenabled   boolean     NOT NULL DEFAULT true,
    lead_id     integer     NULL REFERENCES staff (staff_id),
    noalerts    boolean     NOT NULL DEFAULT false,
    notes       text        NULL,
    created     timestamptz NOT NULL DEFAULT now(),
    updated     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT team_name_key UNIQUE (name)
);

-- ---------------------------------------------------------------------------
-- team_member — staff-to-team membership (FS-091, entity 10).
-- Composite primary key (team_id, staff_id); `updated` timestamp per spec.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_member (
    team_id     integer NOT NULL REFERENCES team (team_id) ON DELETE CASCADE,
    staff_id    integer NOT NULL REFERENCES staff (staff_id) ON DELETE CASCADE,
    updated     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT team_member_pkey PRIMARY KEY (team_id, staff_id)
);

-- ---------------------------------------------------------------------------
-- help_topic — public/internal request category and routing defaults
-- (FS-091, entity 11). Unique constraint on (topic, topic_pid) per BS-091.5.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS help_topic (
    topic_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_pid   integer     NOT NULL DEFAULT 0,
    topic       text        NOT NULL,
    isactive    boolean     NOT NULL DEFAULT true,
    ispublic    boolean     NOT NULL DEFAULT true,
    noautoresp  boolean     NOT NULL DEFAULT false,
    priority_id integer     NOT NULL DEFAULT 2,
    dept_id     integer     NULL REFERENCES department (dept_id),
    staff_id    integer     NULL REFERENCES staff (staff_id),
    team_id     integer     NULL REFERENCES team (team_id),
    sla_id      integer     NULL REFERENCES sla (id),
    page_id     integer     NOT NULL DEFAULT 0,
    sort        integer     NOT NULL DEFAULT 0,
    notes       text        NULL,
    created     timestamptz NOT NULL DEFAULT now(),
    updated     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT help_topic_topic_pid_key UNIQUE (topic, topic_pid)
);

-- ---------------------------------------------------------------------------
-- ticket_lock — exclusive edit lock (FS-021.18, entity 4 in FS-091).
-- Unique on ticket_id (one lock per ticket at a time).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ticket_lock (
    lock_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   bigint      NOT NULL REFERENCES ticket (ticket_id) ON DELETE CASCADE,
    staff_id    integer     NOT NULL REFERENCES staff (staff_id) ON DELETE CASCADE,
    expire      timestamptz NOT NULL,
    created     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ticket_lock_ticket_id_key UNIQUE (ticket_id)
);

-- ---------------------------------------------------------------------------
-- ALTER staff — add show_assigned_only column.
-- Per-staff visibility override: when true, staff sees only tickets assigned
-- to them in queue views.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'staff' AND column_name = 'show_assigned_only'
    ) THEN
        ALTER TABLE staff ADD COLUMN show_assigned_only boolean NOT NULL DEFAULT false;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- ALTER ticket — add closed_by_staff_id column.
-- Records which staff member closed the ticket (for Closed By column in queue).
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'ticket' AND column_name = 'closed_by_staff_id'
    ) THEN
        ALTER TABLE ticket ADD COLUMN closed_by_staff_id integer NULL REFERENCES staff (staff_id);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- ALTER groups — add M3 permission flags.
-- These flags control staff workflow actions in M3.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'groups' AND column_name = 'can_close_tickets'
    ) THEN
        ALTER TABLE groups ADD COLUMN can_close_tickets boolean NOT NULL DEFAULT false;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'groups' AND column_name = 'can_delete_tickets'
    ) THEN
        ALTER TABLE groups ADD COLUMN can_delete_tickets boolean NOT NULL DEFAULT false;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'groups' AND column_name = 'can_assign_tickets'
    ) THEN
        ALTER TABLE groups ADD COLUMN can_assign_tickets boolean NOT NULL DEFAULT false;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'groups' AND column_name = 'can_transfer_tickets'
    ) THEN
        ALTER TABLE groups ADD COLUMN can_transfer_tickets boolean NOT NULL DEFAULT false;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'groups' AND column_name = 'can_edit_tickets'
    ) THEN
        ALTER TABLE groups ADD COLUMN can_edit_tickets boolean NOT NULL DEFAULT false;
    END IF;
END $$;
