-- TS-M3-B1 — add(schema): priority table for sort-by-priority support.
--
-- @implements FS-091.5: priority catalog (ticket_priority entity).
-- @implements FS-020.5: sort by priority urgency requires the priority table.
--
-- Conventions (see 0001_m1_schema_subset.sql):
--   * every object uses IF NOT EXISTS so a second run is a safe no-op.
--   * column/enum literals match FS-091 names for consistency.

-- ---------------------------------------------------------------------------
-- priority — priority catalog (FS-091.5, entity 7).
-- The `ticket.priority_id` column references this table for urgency sorting.
-- Lower `urgency` = more urgent (1 is most urgent, 4 is least).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS priority (
    priority_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority        text        NOT NULL,
    priority_desc   text        NOT NULL,
    priority_color  text        NOT NULL DEFAULT '#FFFFFF',
    urgency         integer     NOT NULL DEFAULT 2,
    ispublic        boolean     NOT NULL DEFAULT true,
    CONSTRAINT priority_priority_key UNIQUE (priority)
);

-- ---------------------------------------------------------------------------
-- Seeded priority rows (FS-091.5 reference data).
-- Matching the spec's seeded priorities table.
-- ---------------------------------------------------------------------------
INSERT INTO priority (priority_id, priority, priority_desc, priority_color, urgency, ispublic)
VALUES
    (1, 'low', 'Low', '#DDFFDD', 4, true),
    (2, 'normal', 'Normal', '#FFFFF0', 3, true),
    (3, 'high', 'High', '#FEE7E7', 2, true),
    (4, 'emergency', 'Emergency', '#FEE7E7', 1, false)
ON CONFLICT (priority_id) DO NOTHING;

-- Reset the sequence to start after the seeded rows
SELECT setval(pg_get_serial_sequence('priority', 'priority_id'), COALESCE(MAX(priority_id), 1)) FROM priority;
