-- TS-M3-C3 — ticket_event lifecycle table (PostgreSQL dialect).
--
-- @implements FS-021.23: Lifecycle event log table.
-- @implements BS-021.14: Annulled flag for event cancellation (e.g., reopen annuls close).
--
-- Records ticket lifecycle events: created, closed, reopened, assigned, transferred, overdue.
-- The annulled flag marks events that have been cancelled (e.g., reopen annuls the prior close).

CREATE TABLE IF NOT EXISTS ticket_event (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id   bigint      NOT NULL REFERENCES ticket (ticket_id) ON DELETE CASCADE,
    staff_id    integer     NULL REFERENCES staff (staff_id),
    team_id     integer     NULL,
    dept_id     integer     NULL REFERENCES department (dept_id),
    topic_id    integer     NULL,
    state       text        NOT NULL,
    username    text        NOT NULL DEFAULT 'SYSTEM',
    annulled    boolean     NOT NULL DEFAULT false,
    created     timestamptz NOT NULL DEFAULT now(),
    -- state values: created, closed, reopened, assigned, transferred, overdue
    CONSTRAINT ticket_event_state_check CHECK (state IN ('created', 'closed', 'reopened', 'assigned', 'transferred', 'overdue'))
);

CREATE INDEX IF NOT EXISTS ticket_event_ticket_id_idx ON ticket_event (ticket_id);
CREATE INDEX IF NOT EXISTS ticket_event_state_idx ON ticket_event (ticket_id, state);
