-- TS-M4-PREP-B — M4 net-new admin tables + SLA transient trump key.
--
-- @implements FS-091: reference data / data model (M4 admin subset).
-- @implements FS-032.13: faq_category entity (FAQ category management).
-- @implements FS-032.16: faq_category public/notes fields.
-- @implements FS-033.11: page entity (site content pages).
-- @implements FS-033.12: page.type set landing|offline|thank-you|other (text + CHECK).
-- @implements FS-033.1: syslog entity (system activity log).
-- @implements FS-033.7: syslog.log_type set Error|Warning|Debug (text + CHECK).
-- @implements BS-033.6: syslog purge support (DEVIATION M4-D2 — writer/purge land later).
-- @implements FS-031.11: timezone reference set (staff Time Zone preference).
-- @implements BS-030-02: email_account model (DEVIATION M4-D1, minimal; M5/FS-040 extends).
-- @implements BS-030-03: template_group model (DEVIATION M4-D1, minimal; M5/FS-040 extends).
-- @implements FS-021.13: SLA transient/explicit-trump precedence slot (sla.transient).
--
-- Conventions (see 0001_m1_schema_subset.sql):
--   * every object uses IF NOT EXISTS / guarded ADD COLUMN so a second run is a
--     safe no-op (idempotency AC).
--   * enum-valued columns are text + CHECK (NOT native PG enum types).
--   * `offset` is a PG reserved word → the timezone column is named `gmt_offset`.
--
-- Ordering note: this migration (0010) creates the tables that the additive FK
-- columns in 0011 (department.email_id/tpl_id/manager_id, staff.timezone_id)
-- reference, so it MUST run before 0011.

-- ---------------------------------------------------------------------------
-- email_account — MINIMAL email identity (DEVIATION M4-D1). The department
-- Email select + FS-032 Emails tab resolve against real rows here. M5/FS-040
-- extends this with fetch (POP3/IMAP) + SMTP columns.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS email_account (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    text        NOT NULL,
    name     text        NOT NULL DEFAULT '',
    active   boolean     NOT NULL DEFAULT true,
    created  timestamptz NOT NULL DEFAULT now(),
    updated  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT email_account_email_key UNIQUE (email)
);

-- ---------------------------------------------------------------------------
-- template_group — MINIMAL email-template set (DEVIATION M4-D1). The department
-- Template select + FS-032 defaults resolve against real rows here. `0` remains
-- the "system default template" sentinel (BS-030-03). M5/FS-040 extends with the
-- per-message template bodies.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS template_group (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text        NOT NULL,
    isactive  boolean     NOT NULL DEFAULT true,
    notes     text        NULL,
    created   timestamptz NOT NULL DEFAULT now(),
    updated   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT template_group_name_key UNIQUE (name)
);

-- ---------------------------------------------------------------------------
-- timezone — offset reference set (FS-031.11). `gmt_offset` avoids the `offset`
-- reserved word. `dst` marks a zone that observes daylight saving.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS timezone (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gmt_offset  numeric(4,2) NOT NULL DEFAULT 0,
    name        text         NOT NULL,
    dst         boolean      NOT NULL DEFAULT false,
    CONSTRAINT timezone_name_key UNIQUE (name)
);

-- ---------------------------------------------------------------------------
-- page — site content page (FS-033.11-.16). `type` is one of the four literals
-- (text + CHECK). `name` unique. `help_topic.page_id` remains a loose integer
-- (0 = unbound sentinel) and is NOT tightened into a real FK here.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS page (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text        NOT NULL,
    type      text        NOT NULL DEFAULT 'other',
    body      text        NOT NULL DEFAULT '',
    isactive  boolean     NOT NULL DEFAULT true,
    notes     text        NULL,
    created   timestamptz NOT NULL DEFAULT now(),
    updated   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT page_name_key UNIQUE (name),
    CONSTRAINT page_type_check CHECK (type IN ('landing', 'offline', 'thank-you', 'other'))
);

-- ---------------------------------------------------------------------------
-- faq_category — knowledge-base category (FS-032.13/.16). `ispublic` toggles
-- client visibility.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS faq_category (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text        NOT NULL,
    ispublic     boolean     NOT NULL DEFAULT true,
    description  text        NOT NULL DEFAULT '',
    notes        text        NULL,
    created      timestamptz NOT NULL DEFAULT now(),
    updated      timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- syslog — system activity log (FS-033.1-.8, DEVIATION M4-D2). `log_type` is one
-- of Error|Warning|Debug (text + CHECK). The writer + purge path land in M4-G;
-- this migration creates the backing store only.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS syslog (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_type    text        NOT NULL DEFAULT 'Error',
    title       text        NOT NULL DEFAULT '',
    log         text        NOT NULL DEFAULT '',
    ip_address  text        NOT NULL DEFAULT '',
    created     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT syslog_log_type_check CHECK (log_type IN ('Error', 'Warning', 'Debug'))
);

CREATE INDEX IF NOT EXISTS syslog_created_idx ON syslog (created);

-- ---------------------------------------------------------------------------
-- ALTER sla — add the transient/explicit-trump precedence column (FS-021.13).
-- The table is `sla` (0001), not `sla_plan`; the FS text says "sla_plan" for
-- parity. Guarded so a re-apply is a no-op.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'sla' AND column_name = 'transient'
    ) THEN
        ALTER TABLE sla ADD COLUMN transient boolean NOT NULL DEFAULT false;
    END IF;
END $$;
